Before tryCatch(tryFunc, nil, onFinally)
Before throwsError
Inside throwsError
Inside onFinally
tryCatch(main, ..) = threw
