


def throwsError() Never:
  print("Inside throwsError")
  final x Any = "hello"
  print(x.bar)


def main():

  def tryFunc() String:
    print("Before throwsError")
    throwsError()
    print("After throwsError")

  def onFinally():
    print("Inside onFinally")

  print("Before tryCatch(tryFunc, nil, onFinally)")
  final result = tryCatch(tryFunc, nil, onFinally)
  print("After tryCatch(tryFunc, nil, onFinally)")
  print("result = %s" % [result])

print("tryCatch(main, ..) = %s" % [tryCatch(main, def(): "threw")])
